#!/bin/bash

if [ "$SNAP_ARCH" = "amd64" ]; then
    ARCH="x86_64-linux-gnu"
elif [ "$SNAP_ARCH" = "armhf" ]; then
    ARCH="arm-linux-gnueabihf"
elif [ "$SNAP_ARCH" = "arm64" ]; then
    ARCH="aarch64-linux-gnu"
elif [ "$SNAP_ARCH" = "ppc64el" ]; then
    ARCH="powerpc64le-linux-gnu"
else
    ARCH="$SNAP_ARCH-linux-gnu"
fi

export LD_LIBRARY_PATH="$SNAP/kf6/usr/lib/$ARCH:$SNAP/kf6/usr/lib:$SNAP/kf6/usr/lib/$ARCH/libproxy:$SNAP/kf6/lib/$ARCH:$SNAP/usr/lib/$ARCH:$LD_LIBRARY_PATH"
export PYTHONPATH="$SNAP/usr/lib/python3/dist-packages"

exec "$@"
