name: picard
grade: stable
confinement: strict
base: core18
adopt-info: picard

apps:
  picard:
    common-id: org.musicbrainz.Picard
    command: bin/picard
    environment:
      DISABLE_WAYLAND: 1
      QT_QPA_PLATFORMTHEME: gtk3
    extensions:
      - kde-neon
    plugs:
      - gsettings
      - home
      - network
      - network-bind
      - network-manager-observe
      - opengl
      - optical-drive
      - pulseaudio
      - removable-media
      - unity7

slots:
  session-dbus-interface:
    interface: dbus
    name: org.musicbrainz.Picard.desktop
    bus: session

parts:
  picard:
    after:
      - patching
      - selective-checkout

    source: https://github.com/metabrainz/picard.git
    #source-depth: 1000
    plugin: python
    requirements:
      - "${SNAPCRAFT_STAGE}/patching/requirements.txt"
    parse-info:
      - share/metainfo/org.musicbrainz.Picard.appdata.xml
    override-pull: |
      snapcraftctl pull
      "$SNAPCRAFT_STAGE"/scriptlets/selective-checkout \
                        --release-tag-prefix='release-' \
                        --stable-tag-pattern=^[[:digit:]].[[:digit:]]\(.[[:digit:]]\)?$ \
                        --beta-tag-pattern=^[[:digit:]].[[:digit:]].[[:digit:]]b[[:digit:]]$ \
                        --release-candidate-tag-pattern=^[[:digit:]].[[:digit:]].[[:digit:]]rc[[:digit:]]$

    override-build: |
      git apply --verbose "${SNAPCRAFT_STAGE}"/patching/*.patch
      snapcraftctl build
    stage-packages:
      - libchromaprint-tools
      - libdiscid0
      - libgettextpo0

      # gtk-common-themes support
      - qt5-gtk-platformtheme

    build-packages:
      - appstream
      - gettext

  # Code patching to fix another part, when it cannot be solved by other means
  patching:
    source: patching
    plugin: dump
    organize:
      '*': patching/
    prime:
      - -*

  # Check out the tagged release revision if it isn't promoted to the stable channel
  # https://forum.snapcraft.io/t/selective-checkout-check-out-the-tagged-release-revision-if-it-isnt-promoted-to-the-stable-channel/10617
  selective-checkout:
    plugin: nil
    build-packages:
      - git
    stage-snaps:
      - selective-checkout
    prime:
      - -*

layout:
    /usr/share/locale:
        bind: $SNAP/share/locale
