name: picard
grade: stable
confinement: strict
base: core24
license: GPL-2.0-or-later
adopt-info: picard
contact: https://community.metabrainz.org/c/picard
donation: https://metabrainz.org/donate
issues: https://tickets.metabrainz.org/projects/PICARD/issues/
source-code: https://github.com/metabrainz/picard
website: https://picard.musicbrainz.org/

platforms:
  amd64:
  arm64:

apps:
  picard:
    extensions:
      - kde-neon-6
    common-id: org.musicbrainz.Picard
    command: bin/picard
    environment:
      PYTHONPATH: "$SNAP/usr/lib/python3/dist-packages"
    plugs:
      - gsettings
      - home  # At a minimum users should be allowed to tag files on their home directory
      - network-manager-observe  # Used by Qt6, required to avoid warnings on startup
      - optical-drive  # CD lookup support
      - removable-media  # Tagging files on external media is a common use case
    command-chain:
      - bin/app-launch

  plugins:
    command: bin/picard-plugins
    environment:
      PYTHONPATH: "$SNAP/usr/lib/python3/dist-packages"
    command-chain:
      - snap/command-chain/desktop-launch

  fpcalc:
    command: usr/bin/fpcalc
    plugs:
      - home
      - removable-media
    command-chain:
      - snap/command-chain/desktop-launch

  rsgain:
    command: usr/bin/rsgain
    plugs:
      - home
      - removable-media
    command-chain:
      - snap/command-chain/desktop-launch

package-repositories:
  - type: apt
    url: http://origin.archive.neon.kde.org/user
    suites: [noble]
    components: [main]
    architectures: [amd64, arm64]
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D

parts:
  picard:
    after:
      - pyqt6
      - selective-checkout
    source: https://github.com/metabrainz/picard.git
    source-branch: master
    # source-tag: release-3.0.0a4
    # source-depth: 1
    plugin: python
    parse-info:
      - share/metainfo/org.musicbrainz.Picard.appdata.xml

    override-build: |
      "$CRAFT_STAGE"/scriptlets/selective-checkout \
        --release-tag-prefix="release-" \
        --stable-tag-pattern="[[:digit:]]+\.[[:digit:]]+(\.[[:digit:]]+)?$" \
        --beta-tag-pattern="[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+b[[:digit:]]+$"
        # --release-candidate-tag-pattern="[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+rc[[:digit:]]+$"
      craftctl default

    python-packages:
      - OpenCC  # opencc plugin
      - zstandard  # xqaf plugin
    stage-packages:
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-good
      - libchromaprint-tools
    stage:
      # PyQt installed from requirements, exclude as the snap includes its own PyQt build
      - -lib/python3*/site-packages/PyQt6*
      - -lib/python3*/site-packages/pyqt6*
    prime:
      # Unused binaries
      - -bin/activate*
      - -bin/Activate.ps1
      - -bin/markdown_py
      - -bin/mid3*
      - -bin/moggsplit
      - -bin/mutagen-*
      - -bin/normalizer
      - -bin/pip*
      - -bin/pylupdate6
      - -bin/pyuic6
      # Exclude development files
      - -include/*
      - -usr/include/*
      - -usr/lib/*-linux-gnu/pkgconfig/*
      # Exclude unused libraries
      - -usr/lib/*-linux-gnu/libcaca++.so*
      - -usr/lib/*-linux-gnu/libcjson_utils.so*
      - -usr/lib/*-linux-gnu/libcolordprivate.so*
      - -usr/lib/*-linux-gnu/libdconf.so*
      - -usr/lib/*-linux-gnu/libEGL_mesa.so*
      - -usr/lib/*-linux-gnu/libexslt.so*
      - -usr/lib/*-linux-gnu/libfaad_drm.so*
      - -usr/lib/*-linux-gnu/libflite*.so*
      - -usr/lib/*-linux-gnu/libform.so*
      - -usr/lib/*-linux-gnu/libfreebl*.so*
      - -usr/lib/*-linux-gnu/libGLX_mesa.so*
      - -usr/lib/*-linux-gnu/libgstcheck-*.so*
      - -usr/lib/*-linux-gnu/libgstcontroller-*.so*
      - -usr/lib/*-linux-gnu/libgstdxva-*.so*
      - -usr/lib/*-linux-gnu/libgstplay-*.so*
      - -usr/lib/*-linux-gnu/libgstplayer-*.so*
      - -usr/lib/*-linux-gnu/libgsttranscoder-*.so*
      - -usr/lib/*-linux-gnu/libhwy_contrib.so*
      - -usr/lib/*-linux-gnu/libhwy_test.so*
      - -usr/lib/*-linux-gnu/libicuio.so*
      - -usr/lib/*-linux-gnu/libicutest.so*
      - -usr/lib/*-linux-gnu/libicutu.so*
      - -usr/lib/*-linux-gnu/libjacknet.so*
      - -usr/lib/*-linux-gnu/libjackserver.so*
      - -usr/lib/*-linux-gnu/libmenu.so*
      - -usr/lib/*-linux-gnu/libmfx-tracer.so*
      - -usr/lib/*-linux-gnu/libmfx-tracer.so*
      - -usr/lib/*-linux-gnu/libmfxhw64.so*
      - -usr/lib/*-linux-gnu/libnssckbi.so
      - -usr/lib/*-linux-gnu/libnssdbm3.so
      - -usr/lib/*-linux-gnu/libOpenEXRCore-*.so*
      - -usr/lib/*-linux-gnu/libOpenEXRUtil-*.so*
      - -usr/lib/*-linux-gnu/liborc-test-*.so*
      - -usr/lib/*-linux-gnu/libpanel.so*
      - -usr/lib/*-linux-gnu/libsmime3.so*
      - -usr/lib/*-linux-gnu/libsoftokn3.so*
      - -usr/lib/*-linux-gnu/libSoundTouchDll.so*
      - -usr/lib/*-linux-gnu/libssl3.so
      - -usr/lib/*-linux-gnu/libunwind-*.so*
      - -usr/lib/*-linux-gnu/libxcb-glx.so*
      - -usr/lib/*-linux-gnu/libXxf86vm.so*
      - -usr/lib/*-linux-gnu/libzvbi-chains.so*

  pyqt6:
    plugin: nil
    source: https://files.pythonhosted.org/packages/8b/47/b25c13eca5bebc6505394d0223e46d7ebf0c57dcac2ed908d7d19b18ab6b/pyqt6-6.11.0.tar.gz
    source-type: tar
    source-checksum: sha256/45dd60aa69976de1918b5ced6b4e7b6a25abd2a919ecef5fd5826ecc76718889
    build-snaps:
      - kde-qt6-core24-sdk
    build-packages:
      - libvulkan-dev
      - python3-pip
    override-build: |
      # Set path to qmake
      echo "[tool.sip.builder]" >> pyproject.toml
      echo "qmake = \"/snap/kde-qt6-core24-sdk/current/usr/bin/qt6/qmake\"" >> pyproject.toml

      # Install build dependencies
      pip install --break-system-packages PyQt6-sip PyQt-builder

      # Build PyQt6
      export LD_LIBRARY_PATH="/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:/snap/kde-qt6-core24-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$LD_LIBRARY_PATH"
      export CFLAGS="-I/snap/kde-qt6-core24-sdk/current/usr/include ${CFLAGS:-}"
      export CXXFLAGS="-I/snap/kde-qt6-core24-sdk/current/usr/include ${CXXFLAGS:-}"
      export LDFLAGS="-L/snap/kde-qt6-core24-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR ${LDFLAGS:-}"
      sip-install \
        --qt-shared \
        --concatenate=1 \
        --confirm-license \
        --debug \
        --verbose \
        --jobs="$CRAFT_PARALLEL_BUILD_COUNT" \
        --target-dir="$CRAFT_PART_INSTALL/lib/python3.12/site-packages" \
        --enable=QtCore \
        --enable=QtDBus \
        --enable=QtGui \
        --enable=QtMultimedia \
        --enable=QtNetwork \
        --enable=QtWidgets \
        --no-dbus-python \
        --no-designer-plugin \
        --no-docstrings \
        --no-qml-plugin \
        --no-tools \
        --qmake-setting QMAKE_CFLAGS="$CFLAGS" \
        --qmake-setting QMAKE_CXXFLAGS="$CXXFLAGS" \
        --qmake-setting QMAKE_LFLAGS="$LDFLAGS"

      # The sip.cpython-*.so file is required for PyQt6 during runtime
      install /usr/local/lib/python3.12/dist-packages/PyQt6/sip.cpython-*.so "$CRAFT_PART_INSTALL/lib/python3.12/site-packages/PyQt6"

  # Qt6Multimedia is not included in the kde-neon base snap
  qt6multimedia:
    after:
      - cleanup  # ensure files get copied after the cleanup ran
    plugin: nil
    stage-packages:
      - libqt6multimedia6
    stage:
      # Only include the necessary Qt6Multimedia files
      - usr/lib/*-linux-gnu/libQt6Multimedia.so*
      - usr/lib/*-linux-gnu/qt6/plugins/multimedia/libffmpegmediaplugin.so
      - usr/lib/*-linux-gnu/qt6/plugins/multimedia/libgstreamermediaplugin.so
      - usr/share/doc/libqt6multimedia6/copyright

  libdiscid:
    plugin: cmake
    source: https://data.metabrainz.org/pub/musicbrainz/libdiscid/libdiscid-0.6.5.tar.gz
    source-type: tar
    source-checksum: sha256/72dbb493e07336418fe2056f0ebc7ce544eedb500bb896cc1cc04bd078c2d530
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
    prime:
      - -usr/include/*
      - -usr/lib/x86_64-linux-gnu/pkgconfig/*

  rsgain:
    plugin: cmake
    source: https://github.com/complexlogic/rsgain/releases/download/v3.7/rsgain-3.7-source.tar.xz
    source-type: tar
    source-checksum: sha256/54037f73ba6682f9b71b2265275f5f89de50b90b12d5af512287c60d9d52c9cc
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
    build-packages:
      - build-essential
      - libavcodec-dev
      - libavformat-dev
      - libavutil-dev
      - libebur128-dev
      - libfmt-dev
      - libinih-dev
      - libswresample-dev
      - libtag1-dev
      - pkg-config
    stage-packages:
      - libavformat60
      - libbluray2
      - libebur128-1
      - libfmt9
      - libinih1
      - libssh-gcrypt-4
      - libtag1v5
    prime:
      - -usr/lib/*-linux-gnu/libcjson_utils.so*
      - -usr/lib/*-linux-gnu/libhwy_contrib.so*
      - -usr/lib/*-linux-gnu/libhwy_test.so*
      - -usr/lib/*-linux-gnu/libicuio.so*
      - -usr/lib/*-linux-gnu/libicutest.so*
      - -usr/lib/*-linux-gnu/libicutu.so*
      - -usr/lib/*-linux-gnu/libzvbi-chains.so*

  # Custom launch scripts
  command-chain:
    plugin: dump
    source: command-chain
    organize:
      '*': bin/

  # Check out the tagged release revision if it isn't promoted to the stable channel
  # https://forum.snapcraft.io/t/selective-checkout-check-out-the-tagged-release-revision-if-it-isnt-promoted-to-the-stable-channel/10617
  selective-checkout:
    source: https://github.com/Lin-Buo-Ren/selective-checkout.git
    source-tag: v3.0.6
    plugin: dump
    build-packages:
      - curl
      - jq
      - sed
      - git
    stage:
      - scriptlets/selective-checkout
    prime:
      - -*

  cleanup:
    after:
      - picard
      - libdiscid
      - rsgain
    plugin: nil
    build-snaps:
      - core24
      - kf6-core24
    override-prime: |
      # Remove duplicate files in the dependent snaps from the final snap.
      for snap in "core24" "kf6-core24"; do
        cd "/snap/$snap/current/usr"
        find . -type f,l -print | sed 's|^./|/root/prime/usr/|' | xargs rm -f
      done

      # Fully remove additional files from the final snap.
      rm -rf /root/prime/usr/lib/*-linux-gnu/directfb-*
      rm -rf /root/prime/usr/lib/*-linux-gnu/dri/*
      rm -rf /root/prime/usr/lib/*-linux-gnu/gbm/*
      rm -rf /root/prime/usr/lib/*-linux-gnu/gstreamer-1.0/*
      rm -rf /root/prime/usr/lib/*-linux-gnu/libbs2b.so*
      rm -rf /root/prime/usr/lib/*-linux-gnu/libdecor-0.so*
      rm -rf /root/prime/usr/lib/*-linux-gnu/libdirect-1.7.so*
      rm -rf /root/prime/usr/lib/*-linux-gnu/libdirectfb-1.7.so*
      rm -rf /root/prime/usr/lib/*-linux-gnu/libdrm_amdgpu.so*
      rm -rf /root/prime/usr/lib/*-linux-gnu/libdrm_intel.so*
      rm -rf /root/prime/usr/lib/*-linux-gnu/libfluidsynth.so*
      rm -rf /root/prime/usr/lib/*-linux-gnu/libfreeaptx.so*
      rm -rf /root/prime/usr/lib/*-linux-gnu/libfusion-*.so*
      rm -rf /root/prime/usr/lib/*-linux-gnu/libgallium-*.so*
      rm -rf /root/prime/usr/lib/*-linux-gnu/libGLESv2.so*
      rm -rf /root/prime/usr/lib/*-linux-gnu/libjack.so*
      rm -rf /root/prime/usr/lib/*-linux-gnu/liblc3.so*
      rm -rf /root/prime/usr/lib/*-linux-gnu/libldacBT_enc.so*
      rm -rf /root/prime/usr/lib/*-linux-gnu/liblilv-0.so*
      rm -rf /root/prime/usr/lib/*-linux-gnu/libLLVM.so*
      rm -rf /root/prime/usr/lib/*-linux-gnu/liblmfx.so*
      rm -rf /root/prime/usr/lib/*-linux-gnu/liblrdf.so*
      rm -rf /root/prime/usr/lib/*-linux-gnu/libltc.so*
      rm -rf /root/prime/usr/lib/*-linux-gnu/libmfx.so*
      rm -rf /root/prime/usr/lib/*-linux-gnu/libmjpegutils-*.so*
      rm -rf /root/prime/usr/lib/*-linux-gnu/libmodplug.so*
      rm -rf /root/prime/usr/lib/*-linux-gnu/libmpeg2encpp-*.so*
      rm -rf /root/prime/usr/lib/*-linux-gnu/libmplex2-*.so*
      rm -rf /root/prime/usr/lib/*-linux-gnu/libneon.so*
      rm -rf /root/prime/usr/lib/*-linux-gnu/libopenh264.so*
      rm -rf /root/prime/usr/lib/*-linux-gnu/libOpenNI2.so*
      rm -rf /root/prime/usr/lib/*-linux-gnu/libraptor2.so*
      rm -rf /root/prime/usr/lib/*-linux-gnu/libsbc.so*
      rm -rf /root/prime/usr/lib/*-linux-gnu/libSDL3.so*
      rm -rf /root/prime/usr/lib/*-linux-gnu/libsensors.so*
      rm -rf /root/prime/usr/lib/*-linux-gnu/libsord-0.so*
      rm -rf /root/prime/usr/lib/*-linux-gnu/libSoundTouch.so*
      rm -rf /root/prime/usr/lib/*-linux-gnu/libspandsp.so*
      rm -rf /root/prime/usr/lib/*-linux-gnu/libsratom-0.so*
      rm -rf /root/prime/usr/lib/*-linux-gnu/libsratom.so*
      rm -rf /root/prime/usr/lib/*-linux-gnu/libsrtp2.so*
      rm -rf /root/prime/usr/lib/*-linux-gnu/libvo-aacenc.so*
      rm -rf /root/prime/usr/lib/*-linux-gnu/libvo-amrwbenc.so*
      rm -rf /root/prime/usr/lib/*-linux-gnu/libvulkan.so*
      rm -rf /root/prime/usr/lib/*-linux-gnu/libWildMidi.so*
      rm -rf /root/prime/usr/lib/*-linux-gnu/libxcb-present.so*
      rm -rf /root/prime/usr/lib/*-linux-gnu/libxcb-randr.so*
      rm -rf /root/prime/usr/lib/*-linux-gnu/libxcb-sync.so*
      rm -rf /root/prime/usr/lib/*-linux-gnu/libxcb-xfixes.so*
      rm -rf /root/prime/usr/lib/*-linux-gnu/libXdamage.so*
      rm -rf /root/prime/usr/lib/*-linux-gnu/libxshmfence.so*
      rm -rf /root/prime/usr/lib/*-linux-gnu/libyajl.so*
      rm -rf /root/prime/usr/lib/*-linux-gnu/libzbar.so*
      rm -rf /root/prime/usr/lib/*-linux-gnu/libzix-0.so*
      rm -rf /root/prime/usr/lib/*-linux-gnu/libserd-0.so*
      rm -rf /root/prime/usr/lib/udev/rules.d/*
      rm -rf /root/prime/usr/share/directfb-*
      rm -rf /root/prime/usr/share/fonts
      rm -rf /root/prime/usr/share/gtk-3.0
      rm -rf /root/prime/usr/share/sounds

      # Remove broken symlinks
      find /root/prime/ -xtype l  -delete

      # Remove empty directories
      find /root/prime/ -depth -type d -empty -delete

lint:
  ignore:
    - library:
      - usr/lib/*-linux-gnu/libdiscid.so*
