name: picard
version: '2.1.3'
summary: Picard is the official MusicBrainz tagger.
description: |
  Picard supports the majority of audio file formats, is capable of using
  audio fingerprints (AcoustIDs), performing CD lookups and disc ID submissions,
  and it has excellent Unicode support. Additionally, there are several plugins
  available that extend Picard's features.

grade: stable
confinement: strict
icon: picard.svg
base: core18

apps:
  picard:
    command: desktop-launch ${SNAP}/bin/picard
    environment:
        DISABLE_WAYLAND: 1
    plugs:
      - gsettings
      - home
      - network
      - network-bind
      - pulseaudio
      - unity7
      - x11
      - optical-drive
      - wayland
      - desktop
      - opengl
      - removable-media

parts:
  picard:
    after:
    - patching

    source: https://github.com/metabrainz/picard.git
    source-depth: 1000
    source-tag: release-2.1.3
    plugin: x-python
    override-build: |
      git apply --verbose "${SNAPCRAFT_STAGE}"/patching/localedir.patch

      snapcraftctl build
    stage-packages:
      - libgettextpo0
      - libchromaprint-tools
      - python3-libdiscid
        #- python-qt4
      - python3-mutagen
        #- gconf2
        #- dconf-cli
        #- libcanberra-gtk-module
        #- overlay-scrollbar-gtk2
        #- unity-gtk2-module
        #- hicolor-icon-theme
        #- libatk-adaptor
        #- libgail-common
      - python3-pyqt5
      - gettext
      - qtwayland5
    build-packages:
      - appstream

  # Part for supporting various desktop technologies
  # Refer: https://github.com/ubuntu/snapcraft-desktop-helpers/blob/master/snapcraft.yaml
  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-depth: 1
    source-subdir: qt

    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    stage-packages:
    - libxkbcommon0
    - ttf-ubuntu-font-family
    - dmz-cursor-theme
    - light-themes
    - adwaita-icon-theme
    - gnome-themes-standard
    - shared-mime-info
    - libqt5gui5
    - libgdk-pixbuf2.0-0
    - libqt5svg5 # for loading icon themes which are svg
    - try: [appmenu-qt5] # not available on core18
    - locales-all
    - xdg-user-dirs
    - fcitx-frontend-qt5

  # Code patching to fix another part, when it cannot be solved by other means
  patching:
    source: patching
    plugin: dump
    organize:
      '*': patching/
    prime:
    - -*
