name: picard
version: '1.4.2'
summary: Picard is the official MusicBrainz tagger.
description: |
  Picard supports the majority of audio file formats, is capable of using
  audio fingerprints (AcoustIDs), performing CD lookups and disc ID submissions,
  and it has excellent Unicode support. Additionally, there are several plugins
  available that extend Picard's features.

grade: stable
confinement: strict
icon: picard.svg
base: core18

apps:
  picard:
    command: desktop-launch ${SNAP}/bin/picard
    plugs:
      - gsettings
      - home
      - network
      - network-bind
      - pulseaudio
      - unity7
      - x11
      - optical-drive

parts:
  picard:
    source: https://github.com/metabrainz/picard
    source-type: git
    source-tag: release-2.0.4
    plugin: python
    # prepare: git apply $SNAPCRAFT_STAGE/disable-gconf.patch
    build-packages:
      - pyqt5-dev-tools
    stage-packages:
      - libgettextpo0
      - libchromaprint-tools
      - python-libdiscid
      - python-qt4
      - python-mutagen
      - gconf2
      - dconf-cli
      - libcanberra-gtk-module
      - overlay-scrollbar-gtk2
      - unity-gtk2-module
      - hicolor-icon-theme
      - libatk-adaptor
      - libgail-common
      - python3-pyqt5
    after:
      - desktop-qt5
      # - patches
    #patches:
      #source: snap/patches
      #plugin: dump
      #prime:
        #- -*
