name: picard
grade: stable
confinement: strict
base: core20
license: GPL-2.0-or-later
adopt-info: picard
contact: https://community.metabrainz.org/c/picard
donation: https://metabrainz.org/donate
issues: https://tickets.metabrainz.org/projects/PICARD/issues/
source-code: https://github.com/metabrainz/picard
website: https://picard.musicbrainz.org/

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

apps:
  picard:
    common-id: org.musicbrainz.Picard
    command: bin/picard
    environment:
      DISABLE_WAYLAND: 1
      QT_QPA_PLATFORMTHEME: gtk3
      PYTHONPATH: "$SNAP/usr/lib/python3/dist-packages"
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - gsettings
      - home
      - network
      - network-bind
      - network-manager-observe
      - opengl
      - optical-drive
      - audio-playback
      - pulseaudio  # For eventual backwards compatibility only
      - removable-media
      - unity7
    command-chain:
      - bin/desktop-launch
      - bin/app-launch

plugs:
  # Support for common GTK themes
  # https://forum.snapcraft.io/t/how-to-use-the-system-gtk-theme-via-the-gtk-common-themes-snap/6235
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes

parts:
  picard:
    after:
      - desktop-qt5
      - qt5-gtk-platform
      - qt5-multimedia
      - rsgain
      - selective-checkout
    source: https://github.com/metabrainz/picard.git
    # source-tag: release-2.8.5
    # source-depth: 1
    plugin: python
    # requirements:
    #   - requirements.txt
    parse-info:
      - share/metainfo/org.musicbrainz.Picard.appdata.xml

    override-pull: |
      snapcraftctl pull
      "$SNAPCRAFT_STAGE"/scriptlets/selective-checkout \
        --release-tag-prefix="release-" \
        --stable-tag-pattern="[[:digit:]]+\.[[:digit:]]+(\.[[:digit:]]+)?$" \
        --beta-tag-pattern="[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+b[[:digit:]]+$" \
        --release-candidate-tag-pattern="[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+rc[[:digit:]]+$"

    override-build: |
      git apply --verbose "${SNAPCRAFT_PROJECT_DIR}"/patching/picard/*.patch
      snapcraftctl build

    override-prime: |
      snapcraftctl prime
      # Compile resource caches
      glib-compile-schemas $SNAPCRAFT_PRIME/usr/share/glib-2.0/schemas
      update-mime-database $SNAPCRAFT_PRIME/usr/share/mime
      for dir in $SNAPCRAFT_PRIME/usr/share/icons/*; do
        if [ -f "$dir/index.theme" ]; then
          gtk-update-icon-cache --force "$dir"
        fi
      done

    prime:
      - -lib/python3.*/site-packages/PyQt5*
      - -usr/bin/dh_numpy3
      - -usr/bin/f2py3*
      - -usr/include/*
    # build-environment:
    #   - PYTHONPATH: "$SNAPCRAFT_PART_INSTALL/usr/lib/python3/dist-packages"
    build-packages:
      - appstream
      - gettext
      - libgdk-pixbuf2.0-0
      - libglib2.0-bin
      - python3-wheel
    stage-packages:
      - libchromaprint-tools
      - libdiscid0
      - libgettextpo0
      - python3-aubio  # for the BPM plugin
      - python3-pyqt5
      - python3-pyqt5.qtmultimedia

  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - build-essential
      - qtbase5-dev
      - dpkg-dev
    stage-packages:
      - adwaita-icon-theme
      - dmz-cursor-theme
      - fcitx-frontend-qt5
      - gnome-themes-standard
      - libgdk-pixbuf2.0-0
      - libqt5gui5
      - libqt5svg5  # for loading icon themes which are svg
      - libxkbcommon0
      - light-themes
      - locales-all
      - shared-mime-info
      - ttf-ubuntu-font-family
      - xdg-user-dirs

  qt5-gtk-platform:
    plugin: nil
    stage-packages:
      - librsvg2-common  # For SVG icon support in GTK file picker
      - qt5-gtk-platformtheme

  qt5-multimedia:
    plugin: nil
    stage-packages:
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-good
      - libqt5multimedia5-plugins

  rsgain:
    plugin: cmake
    source: https://github.com/complexlogic/rsgain/releases/download/v3.4/rsgain-3.4-source.tar.xz
    source-type: tar
    source-checksum: sha256/392ad1407eea7737c6f63b6a0681a3df51f33033d2d16b644f407e6ef3f28013
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
    build-packages:
      - build-essential
      - libavcodec-dev
      - libavformat-dev
      - libavutil-dev
      - libebur128-dev
      - libfmt-dev
      - libinih-dev
      - libswresample-dev
      - libtag1-dev
      - pkg-config
    stage-packages:
      - libavformat58
      - libbluray2
      - libebur128-1
      - libinih1
      - libssh-gcrypt-4
      - libtag1v5

  # Custom launch scripts
  command-chain:
    plugin: dump
    source: command-chain
    organize:
      '*': bin/

  # Check out the tagged release revision if it isn't promoted to the stable channel
  # https://forum.snapcraft.io/t/selective-checkout-check-out-the-tagged-release-revision-if-it-isnt-promoted-to-the-stable-channel/10617
  selective-checkout:
    source: https://github.com/Lin-Buo-Ren/selective-checkout.git
    source-tag: v3.0.1
    plugin: dump
    build-packages:
      - curl
      - jq
      - sed
      - git
    stage:
      - scriptlets/selective-checkout
    prime:
      - -*
