name: picard
version: '2.0.4'
summary: Picard is the official MusicBrainz tagger.
description: |
  Picard supports the majority of audio file formats, is capable of using
  audio fingerprints (AcoustIDs), performing CD lookups and disc ID submissions,
  and it has excellent Unicode support. Additionally, there are several plugins
  available that extend Picard's features.

grade: stable
confinement: strict
icon: picard.svg
base: core18

apps:
  picard:
    command: desktop-launch ${SNAP}/bin/picard
    environment:
        DISABLE_WAYLAND: 1
    plugs:
      - gsettings
      - home
      - network
      - network-bind
      - pulseaudio
      - unity7
      - x11
      - optical-drive
      - wayland
      - desktop
      - opengl

parts:
  picard:
    source: https://github.com/metabrainz/picard
    source-type: git
    source-tag: release-2.0.4
    plugin: python
    stage-packages:
      - libgettextpo0
      - libchromaprint-tools
      - python3-libdiscid
        #- python-qt4
      - python3-mutagen
        #- gconf2
        #- dconf-cli
        #- libcanberra-gtk-module
        #- overlay-scrollbar-gtk2
        #- unity-gtk2-module
        #- hicolor-icon-theme
        #- libatk-adaptor
        #- libgail-common
      - python3-pyqt5
      - gettext
      - qtwayland5
    organize:
      build/locale/*: share/locale/
    after: [desktop-qt5]
